/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelProjectFinalComplict;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SARK
 */
public class CustomarTotalPayment extends javax.swing.JFrame {

    String a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, s, t;

    /**
     * Creates new form NewJFrame
     */
    public CustomarTotalPayment() {
        initComponents();
        roomNumber();
        showTime();
        Date d = new Date();
        SimpleDateFormat si = new SimpleDateFormat("dd-MM-yyyy");
        jda.setText(si.format(d));
        getContentPane().setBackground(new java.awt.Color(204, 204, 255));
    }

    void showTime() {

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat si = new SimpleDateFormat("hh:mm:ss a");
                jTime.setText(si.format(d));
            }
        }).start();

    }
     private void roomNumber() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");
            Statement stmt = con.createStatement();
            String query = "select roomNum from roomnumber";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
            jroomNum.addItem(rs.getString("roomNum"));
            }
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField13 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jpc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        je = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jDateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jGender = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRoomExt = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jsave = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jDate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtCustomerId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNationality = new com.toedter.components.JLocaleChooser();
        jLabel9 = new javax.swing.JLabel();
        jIdType = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckinDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jCheckOutDate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jMeal = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jRoomType = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jroomNum = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jCustomarMobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jText = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSubTotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnTotalCost1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jda = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTime = new javax.swing.JLabel();

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Check In Date");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Check Out Date :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Room Type:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Room No.  :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Room Ext. No :");

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Address 2 :");

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Post Code :");

        je.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Email :");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jTable.setBackground(new java.awt.Color(255, 0, 205));
        jTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customar_Ref", "Surname", "Address ", "Customar Mobil", "Nationality", "Date of Birth", "Gender", "Check In Date", "Check Out Date", "Room Type", "Room No."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jDateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Date of Birth");

        jGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Gender");

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Firstname :");

        jRoomExt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "010", "020", "030", "040", "050", "060", "070", "080", "090", "100" }));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Room Ext No. :");

        jsave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jsave.setText("Save");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDate.setBackground(new java.awt.Color(0, 153, 255));
        jDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jDate.setForeground(new java.awt.Color(51, 0, 51));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jtxtCustomerId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Customar_Id");

        jName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name");

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Address  :");

        jNationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arabic (United Arab Emirates)", "Arabic (Jordan)", "Arabic (Syria)", "Croatian (Croatia)", "French (Belgium)", "Spanish (Panama)", "Maltese (Malta)", "Spanish (Venezuela)", "Chinese (Taiwan)", "Danish (Denmark)", "Spanish (Puerto Rico)", "Vietnamese (Vietnam)", "English (United States)", "Serbian (Montenegro)", "Swedish (Sweden)", "Spanish (Bolivia)", "English (Singapore)", "Arabic (Bahrain)", "Arabic (Saudi Arabia)", "Arabic (Yemen)", "Hindi (India)", "English (Malta)", "Finnish (Finland)", "Serbian (Latin,Bosnia and Herzegovina)", "Ukrainian (Ukraine)", "French (Switzerland)", "Spanish (Argentina)", "Arabic (Egypt)", "Japanese (Japan,JP)", "Spanish (El Salvador)", "Portuguese (Brazil)", "Icelandic (Iceland)", "Czech (Czech Republic)", "Polish (Poland)", "Catalan (Spain)", "Serbian (Serbia and Montenegro)", "Malay (Malaysia)", "Spanish (Spain)", "Spanish (Colombia)", "Bulgarian (Bulgaria)", "Serbian (Bosnia and Herzegovina)", "Spanish (Paraguay)", "Spanish (Ecuador)", "Spanish (United States)", "Arabic (Sudan)", "Romanian (Romania)", "English (Philippines)", "Arabic (Tunisia)", "Serbian (Latin,Montenegro)", "Spanish (Guatemala)", "Korean (South Korea)", "Greek (Cyprus)", "Spanish (Mexico)", "Russian (Russia)", "Spanish (Honduras)", "Chinese (Hong Kong)", "Norwegian (Norway,Nynorsk)", "Hungarian (Hungary)", "Thai (Thailand)", "Arabic (Iraq)", "Spanish (Chile)", "Arabic (Morocco)", "Irish (Ireland)", "Turkish (Turkey)", "Estonian (Estonia)", "Arabic (Qatar)", "Portuguese (Portugal)", "French (Luxembourg)", "Arabic (Oman)", "Albanian (Albania)", "Spanish (Dominican Republic)", "Spanish (Cuba)", "English (New Zealand)", "Serbian (Serbia)", "German (Switzerland)", "Spanish (Uruguay)", "Greek (Greece)", "Hebrew (Israel)", "English (South Africa)", "Thai (Thailand,TH)", "French (France)", "German (Austria)", "Norwegian (Norway)", "English (Australia)", "Dutch (Netherlands)", "French (Canada)", "Latvian (Latvia)", "German (Luxembourg)", "Spanish (Costa Rica)", "Arabic (Kuwait)", "Arabic (Libya)", "Italian (Switzerland)", "German (Germany)", "Arabic (Algeria)", "Slovak (Slovakia)", "Lithuanian (Lithuania)", "Italian (Italy)", "English (Ireland)", "Chinese (Singapore)", "English (Canada)", "Dutch (Belgium)", "Chinese (China)", "Japanese (Japan)", "German (Greece)", "Serbian (Latin,Serbia)", "English (India)", "Arabic (Lebanon)", "Spanish (Nicaragua)", "Macedonian (Macedonia)", "Belarusian (Belarus)", "Slovenian (Slovenia)", "Spanish (Peru)", "Indonesian (Indonesia)", "English (United Kingdom)", "Bangali (Bangladesh)" }));
        jNationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nationality");

        jIdType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Driving Lic", "Passport", "Pilot Lic", "Student Id." }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("ID Type");

        jCheckinDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Check In Date :");

        jCheckOutDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Check Out Date :");

        jMeal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", " " }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Meal");

        jRoomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Family", " " }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Room Type :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Room No. :");

        jCustomarMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Customar Mobile:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jIdType, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCustomarMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(143, 143, 143)
                                .addComponent(jroomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(134, 134, 134)
                                .addComponent(jRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(109, 109, 109)
                                .addComponent(jCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(119, 119, 119)
                                .addComponent(jCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jCheckinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jroomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCustomarMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 450, 460));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jText.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jText.setForeground(new java.awt.Color(255, 51, 102));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setText("Tax :");

        jSubTotal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jSubTotal.setForeground(new java.awt.Color(255, 51, 51));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 102));
        jLabel24.setText("SubTotal :");

        jTotal.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jTotal.setForeground(new java.awt.Color(255, 102, 102));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 102));
        jLabel25.setText("Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jText, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jSubTotal)
                    .addComponent(jTotal))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 510, 460));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Show");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnReset.setBackground(new java.awt.Color(204, 204, 255));
        jbtnReset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(204, 204, 255));
        jbtnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnTotalCost1.setBackground(new java.awt.Color(204, 204, 255));
        jbtnTotalCost1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnTotalCost1.setText("Total Cost");
        jbtnTotalCost1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnTotalCost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalCost1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton2)
                .addGap(118, 118, 118)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jbtnTotalCost1)
                .addGap(68, 68, 68)
                .addComponent(jButton3)
                .addGap(81, 81, 81)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnTotalCost1)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 564, 1180, 90));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 204));
        jLabel27.setText("Date  :");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 30));

        jda.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jda.setForeground(new java.awt.Color(255, 0, 153));
        jda.setOpaque(true);
        getContentPane().add(jda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 30));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Time");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, -1, 30));

        jTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTime.setForeground(new java.awt.Color(255, 0, 102));
        jTime.setOpaque(true);
        getContentPane().add(jTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 100, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if (jTable.getSelectedRow() == -1) {
            if (jTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data to Delete", "Hotel Management System",
                        JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Select a row to delete ", "Hotel Management System",
                        JOptionPane.OK_OPTION);

            }

        } else {

            model.removeRow(jTable.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Hotel Management System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }


    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if (jTable.getSelectedRow() == -1) {
            if (jTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Hotel Booking Update confirmed", "Hotel Management System",
                        JOptionPane.OK_OPTION);
            }

        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);
        jtxtCustomerId.setText(null);
        jtxtFirstname.setText(null);
        jName.setText(null);
        jtxtAddress.setText(null);
        jpc.setText(null);
        jCustomarMobile.setText(null);
        je.setText(null);
        jNationality.setSelectedIndex(0);
        jDateOfBirth.setDate(null);
        jIdType.setSelectedIndex(0);
        jGender.setSelectedIndex(0);
        jCheckinDate.setDate(null);
        jCheckOutDate.setDate(null);
        jMeal.setSelectedIndex(0);
        jRoomType.setSelectedIndex(0);
        jroomNum.setSelectedIndex(0);
        jRoomExt.setSelectedIndex(0);
        jText.setText(null);
        jSubTotal.setText(null);
        jTotal.setText(null);

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.addRow(new Object[]{
            jtxtCustomerId.getText(),
            // jtxtFirstname.getText(),
            jName.getText(),
            jtxtAddress.getText(),
            // jpc.getText(),
            jCustomarMobile.getText(),
            //je.getText(),
            jNationality.getSelectedItem(),
            // jn.getSelectedIndex(),
            jDateOfBirth.getDate(),
            //jit.getSelectedItem(),
            jGender.getSelectedItem(),
            jCheckinDate.getDate(),
            jCheckOutDate.getDate(),
            //jm.getSelectedItem(),
            jRoomType.getSelectedItem(),
            jroomNum.getSelectedItem(),
            jRoomExt.getSelectedItem(),
            jText.getText(),
            jSubTotal.getText(),
            jTotal.getText(),});
        jtxtCustomerId.getText();
        // jtxtFirstname.getText(),
        jName.getText();
        jtxtAddress.getText();
        // jpc.getText(),
        jCustomarMobile.getText();
        //je.getText(),
        jNationality.getSelectedItem();
        // jn.getSelectedIndex(),
        jDateOfBirth.getDate();
        //jit.getSelectedItem(),
        jGender.getSelectedItem();
        jCheckinDate.getDate();

        jCheckOutDate.getDate();
        jMeal.getSelectedItem();
        jRoomType.getSelectedItem();
        jroomNum.getSelectedItem();
        jRoomExt.getSelectedItem();
        jText.getText();
        jSubTotal.getText();
        jTotal.getText();

    }//GEN-LAST:event_jsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        allRecord();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        allShow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnTotalCost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalCost1ActionPerformed
       int SingleRoom = 800;
        int DoubleRoom = 1200;
        int FamilyRoom = 2000;

        int oneMeal = 100;
        int twoMeals = 200;
        int threeMeals = 400;

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date Check_In_Date = null;
        Date Check_Out_Date = null;

        try {

            Check_In_Date = format.parse(format.format(jCheckinDate.getDate()));
            Check_Out_Date = format.parse(format.format(jCheckOutDate.getDate()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        long Checkdiff = Check_Out_Date.getTime() - Check_In_Date.getTime();
        int Daysdiff = (int) (Checkdiff / 24 / 60 / 60 / 1000);

        //=========================================================================================   
        if (jRoomType.getSelectedItem().equals("Single") && jMeal.getSelectedItem().equals("1")) {
            jTotal.setText(Integer.toString(Daysdiff * (SingleRoom + oneMeal))); // Daysdiff*(SingleRoom+oneMeal);
            jText.setText(Integer.toString(Daysdiff * (SingleRoom + oneMeal)));
            jSubTotal.setText(Integer.toString(Daysdiff * (SingleRoom + oneMeal)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            // st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            // tt=(tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //=======================================================================================
        else if (jRoomType.getSelectedItem().equals("Double") && jMeal.getSelectedItem().equals("1")) {
            jTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + oneMeal)));
            jText.setText(Integer.toString(Daysdiff * (DoubleRoom + oneMeal)));
            jSubTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + oneMeal)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format(("%.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //==================================================================================
        else if (jRoomType.getSelectedItem().equals("Family") && jMeal.getSelectedItem().equals("1")) {
            jTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + oneMeal)));
            jText.setText(Integer.toString(Daysdiff * (FamilyRoom + oneMeal)));
            jSubTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + oneMeal)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //=====================================================================================  
        else if (jRoomType.getSelectedItem().equals("Single") && jMeal.getSelectedItem().equals("2")) {
            jTotal.setText(Integer.toString(Daysdiff * (SingleRoom + twoMeals)));
            jText.setText(Integer.toString(Daysdiff * (SingleRoom + twoMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (SingleRoom + twoMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format(("%.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //+++++++++++++++++++++=======================================================
        else if (jRoomType.getSelectedItem().equals("Double") && jMeal.getSelectedItem().equals("2")) {
            jTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + twoMeals)));
            jText.setText(Integer.toString(Daysdiff * (DoubleRoom + twoMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + twoMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //================================================================================
        else if (jRoomType.getSelectedItem().equals("Family") && jMeal.getSelectedItem().equals("2")) {
            jTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + twoMeals)));
            jText.setText(Integer.toString(Daysdiff * (FamilyRoom + twoMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + twoMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //========================================================================
        else if (jRoomType.getSelectedItem().equals("Single") && jMeal.getSelectedItem().equals("3")) {
            jTotal.setText(Integer.toString(Daysdiff * (SingleRoom + threeMeals)));
            jText.setText(Integer.toString(Daysdiff * (SingleRoom + threeMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (SingleRoom + threeMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        } //=============================================================================
        else if (jRoomType.getSelectedItem().equals("Double") && jMeal.getSelectedItem().equals("3")) {
            jTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + threeMeals)));
            jText.setText(Integer.toString(Daysdiff * (DoubleRoom + threeMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (DoubleRoom + threeMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format(("%.3f"), tt + q);
            jTotal.setText(total);

        } //==================================================================================
        else if (jRoomType.getSelectedItem().equals("Family") && jMeal.getSelectedItem().equals("3")) {
            jTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + threeMeals)));
            jText.setText(Integer.toString(Daysdiff * (FamilyRoom + threeMeals)));
            jSubTotal.setText(Integer.toString(Daysdiff * (FamilyRoom + threeMeals)));

            double q = Double.parseDouble(jText.getText());
            q = (q * 0.25) / 100;
            String tax = String.format((" %.2f"), q);
            jText.setText(tax);

            double st = Double.parseDouble(jSubTotal.getText());
            st = (st);
            String subtotal = String.format((" %.2f"), st);
            jSubTotal.setText(subtotal);

            double tt = Double.parseDouble(jTotal.getText());
            tt = (tt);
            String total = String.format((" %.3f"), tt + q);
            jTotal.setText(total);

        }
        //====================================================================================

//=====================================================================================


String x,y,z;
x = jText.getText();
double ta = Double.parseDouble(x);
y = jSubTotal.getText();
double subTo =  Double.parseDouble(y);
z = jTotal.getText();
double tot =  Double.parseDouble(z);

 Connection con = null;
        Statement stmt = null;

 try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");

            stmt = con.createStatement();
            int count = 0;
            //Execute the query
            count = stmt.executeUpdate("insert into hotelTotal(tax,subTotal,total) values('" + ta + "','" + subTo + "','" + tot+"')");
            if (count > 0) {
                //                System.out.println("inserted successfully");
                JOptionPane.showMessageDialog(this, "inserted successfully");
                // clear();
                //  displayInTable();
            } else {
                //                System.out.println("insertion failed");
                JOptionPane.showMessageDialog(this, "insertion failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jbtnTotalCost1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       HotelManageMent select = new HotelManageMent();
        select.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    private void allShow() {
        String cId = jtxtCustomerId.getText();
        int id = Integer.parseInt(cId);

       // String roomNumber = jroomNum.getSelectedItem().toString();

        // String id = jtxtCustomerId.getText();
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");
            //Create the Statement object
            stmt = con.createStatement();

            //Execute the query
            rs = stmt.executeQuery("select  name, address, nation,id_t,c_i_d ,c_o_d,meal,room_T,room_n,c_m from hotelm where c_id= '" + id + "' ");
            int count = 0;
            while (rs.next()) {
               // jtxtCustomerId.setText(rs.getString("c_id"));
                jName.setText(rs.getString("name"));
                jtxtAddress.setText(rs.getString("address"));
                jNationality.setSelectedItem(rs.getString("nation"));
                jIdType.setSelectedItem(rs.getString("id_t"));
                jCheckinDate.setDate(rs.getDate("c_i_d"));
                jCheckOutDate.setDate(rs.getDate("c_o_d"));
                jMeal.setSelectedItem(rs.getString("meal"));
                jRoomType.setSelectedItem(rs.getString("room_T"));
                jroomNum.setSelectedItem(rs.getString("room_n"));
                jCustomarMobile.setText(rs.getString("c_m"));
//                if (rs.getString("gender").equalsIgnoreCase("male")) {
//                    male.setSelected(true);
//
//                } else {
//                    female.setSelected(true);
//                }
//                String degree = rs.getString("degree");
//                if (degree != null) {
//                    String d[] = degree.split(",");
//                    for (int i = 0; i < d.length; i++) {
//                        System.out.println(d[i] + " ");
//                        if (jCheckBox1.getText().equalsIgnoreCase(d[i])) {
//                            jCheckBox1.setSelected(true);
//                        }
//                        if (jCheckBox2.getText().equalsIgnoreCase(d[i])) {
//                            jCheckBox2.setSelected(true);
//                        } else if (jCheckBox3.getText().equalsIgnoreCase(d[i])) {
//                            jCheckBox3.setSelected(true);
//                        } else if (jCheckBox4.getText().equalsIgnoreCase(d[i])) {
//                            jCheckBox4.setSelected(true);
//                        } else {
//                        }
//                    }
//                }

                count++;
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(rootPane, "There is no such record");
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

    }

    private void allRecord() {
        a = jtxtCustomerId.getText();
        int id = Integer.parseInt(a);

        SimpleDateFormat datf = new SimpleDateFormat("yyyy-MM-dd");
        p = jroomNum.getSelectedItem().toString();

        h = datf.format(jCheckinDate.getDate());

        j = datf.format(jCheckOutDate.getDate());
        if (j.compareTo(h) < 0) {
            JOptionPane.showMessageDialog(this, "select correctly");
            jCheckOutDate.requestFocus();
        }

//       
        Connection con = null;
        Statement stmt = null;

        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");

            stmt = con.createStatement();
            int count = 0;
            //Execute the query
            count = stmt.executeUpdate("insert into hotel(inDate, outDate, roomNum) values('" + h + "','" + j + "','" + p + "')");
            if (count > 0) {
                //                System.out.println("inserted successfully");
                JOptionPane.showMessageDialog(this, "inserted successfully");
                // clear();
                //  displayInTable();
            } else {
                //                System.out.println("insertion failed");
                JOptionPane.showMessageDialog(this, "insertion failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomarTotalPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jCheckOutDate;
    private com.toedter.calendar.JDateChooser jCheckinDate;
    private javax.swing.JTextField jCustomarMobile;
    private javax.swing.JTextField jDate;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateOfBirth;
    private javax.swing.JComboBox jGender;
    private javax.swing.JComboBox jIdType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jMeal;
    private javax.swing.JTextField jName;
    private com.toedter.components.JLocaleChooser jNationality;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox jRoomExt;
    private javax.swing.JComboBox jRoomType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSubTotal;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jText;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jTime;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotalCost1;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel jda;
    private javax.swing.JTextField je;
    private javax.swing.JTextField jpc;
    private javax.swing.JComboBox jroomNum;
    private javax.swing.JButton jsave;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomerId;
    private javax.swing.JTextField jtxtFirstname;
    // End of variables declaration//GEN-END:variables
}
